name: Notify Robots
on:
  push: # 所有分支的 push 事件均触发
    branches-ignore: [] # 不排除任何分支
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码（必须步骤）
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python 环境（用于执行脚本）
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 安装依赖库（requests用于HTTP请求）
      - name: Install dependencies
        run: pip install requests

      # 4. 发送钉钉通知
      # - name: Notify DingTalk
      #   env:
      #     DINGTALK_WEBHOOK: https://oapi.dingtalk.com/robot/send?access_token=1fa397a9958ca9a2e6859689cc02455e473eaf37fbea98331fed4330e30e594b
      #     DINGTALK_SECRET: SEC47e40a9fdb7116a97088a1047cb8d99ade35ab4d2c30aa18d61e3ff4402c4cf2
      #   run: |
      #     python3 .github/workflows/dingtalk_notify.py "${{ github.event.head_commit.message }}" "${{ github.actor }}"

      # 5. 发送飞书通知
      - name: Notify Feishu
        env:
          FEISHU_WEBHOOK: https://open.feishu.cn/open-apis/bot/v2/hook/ed322339-956c-4c86-8467-7a57755bdfc1
        run: |
          python3 .github/workflows/feishu_notify.py "${{ github.event.head_commit.message }}"
